conky.config = {
    alignment = 'top_right',
    gap_x = 96,
    gap_y = 96,

    minimum_width = 520,
    minimum_height = 800,
    maximum_width = 520,

    own_window = true,
    own_window_type = 'override',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_class = 'Conky',
    own_window_title = 'conky-clock',

    background = true,
    update_interval = 2,
    double_buffer = true,
    no_buffers = true,
    use_xft = true,

    border_inner_margin = 0,
    border_outer_margin = 0,

    lua_load = '~/.config/conky/clock/clock.lua',
    lua_draw_hook_post = 'draw_clock',
};

conky.text = [[ ]];
